### ISSUE TITLE
Users created with wrong icon url

### ISSUE THREAD

**Issue by bellisk** [c-e-p/ourchive#133]
**Describe the bug**
I created a new user via registration. The new user's icon url was set to http://127.0.0.1:8000/static/icon-default.png, but should have been https://example.org/static/icon-default.png. (127.0.0.1:8000 is the sample value for `OURCHIVE_ROOT_URL`, but I had changed this to `example.org` on initial setup.)

**To Reproduce**
1. Deploy Ourchive to VPS hosting as described in https://docs.getourchive.io/admin-getting-started/
2. In `.env`, update `OURCHIVE_ROOT_URL` to (e.g.) `example.org` and `OURCHIVE_SERVER_IP` to the actual server IP
3. Create a new user via direct registration, not via requesting an invite (I haven't tested that path)
4. On the user page, instead of an icon, is a broken-image icon
5. Right-click on the image and select "Open image in new tab". The icon url is http://127.0.0.1:8000/static/icon-default.png

**Expected behavior**
The new user's icon should use the correct url, e.g. https://example.org/static/icon-default.png.

**Screenshots**
![Screenshot 2024-04-19 at 22-44-52 User - test_user2](https://github.com/c-e-p/ourchive/assets/903490/225d7dea-961a-4346-b99b-796d3c9653ac)

**Hosting**
Digital Ocean droplet running Ubuntu 22.04.

**Comment by c-e-p** [comment]
Probably an issue with static file handling. Will be fixed with next release.

**Comment by c-e-p** [comment]
Was indeed an issue with static file handling. Validated with new signup in dev.
