### ISSUE TITLE
Error when trying to create new bookmark

### ISSUE THREAD

**Issue by ladyofthelog** [c-e-p/ourchive#34]
As with new works... I get this error when attempting to create a new bookmark. UBlock is disabled, I confirmed in the admin panel that I should have the power to add a new bookmark, and I am using Chrome Version 113.0.5672.92. 

<img width="1236" alt="Screen Shot 2023-05-26 at 1 22 16 AM" src="https://github.com/c-e-p/ourchive/assets/46003573/1f477a16-c94c-49db-97b9-e7312a8363e2">

**Comment by c-e-p** [comment]
Same as the error on new work, we were missing an Origin header in the Python responses call. It didn't break anything locally but broke things behind a reverse proxy. It should now be fixed.
