### ISSUE TITLE
Creator Profile link on work is incorrect

### ISSUE THREAD

**Issue by ladyofthelog** [c-e-p/ourchive#36]
The url for the creator "lost" on https://ourchive-dev.stopthatimp.net/works/1/ points to "https://ourchive-dev.stopthatimp.net/works/1/ourchive-dev.stopthatimp.net/username/lost"

**Comment by c-e-p** [comment]
Same deal as other links, something changed in the way the template builds the links. I removed {{ root }} (which pointed to the root URL) and now it should work.
