### ISSUE TITLE
UI Styling

### ISSUE THREAD

**Issue by c-e-p** [c-e-p/ourchive#4]
- [ ] validate pages at web, tablet & mobile size
- [x] create dark mode 
- [ ] tweak colors until we're happy with them
- [x] add IDs to every div you see
- [x] work metadata, chapter metadata including update time(s)
- [x] bookmark metadata
- [x] collection metadata
- [x] attributes on tiles
- [ ] design homepage
- [x] update design per verity feedback
- [ ] fix dark mode include/exclude toggle highlight reversing
- [ ] Implement tag collapse behavior
- [ ] Implement tag default preferences (default preferred values per tag type)

**Comment by c-e-p** [comment]
@ladyofthelog i just nuked our old theme in favor of a slightly different one that will let us make broad updates. there are some alignment issues etc that need to change like on the tags pages, so consider those 'in progress' per this ticket, but if you have theme suggestions, primary/secondary/tertiary color palette suggestions, etc please add them, as well as "this makes no goddamn sense" type UI stuff.

**Comment by ladyofthelog** [comment]
Hey it's me back with minor quibbles with the UI [I put in a doc ](https://docs.google.com/document/d/1sArm9uFjnVkI5AklMGZmaVsarcRBbD14QXLj2i-PVzA/edit?usp=sharing)

**Comment by c-e-p** [comment]
@ladyofthelog everything on existing document has been addressed except max width. The content container sizes are pretty deep in uikit and I'm not sure I want to mess around with them right now. This might be a non-MVP thing.
