### ISSUE TITLE
Work posting flow improvements

### ISSUE THREAD

**Issue by c-e-p** [c-e-p/ourchive#48]
Work posting currently has some circular logic and user unfriendly flows. Fix the UX! 
* Allow HTML/plaintext editing -> done
* Markdown support? If simple within TinyMCE, otherwise add to 1.0 roadmap -> in 1.0 roadmap
* Fix weird work/chapter saving issues where switching to chapter doesn't save work, saving work redirects to chapter etc --> done
* Evaluate AO3 import for inclusion in MVP --> done
* Pagination should be added to chapter edit view (this is straight-up a bug) -> done
* Add 'publish all' option --> done

**Comment by c-e-p** [comment]
@ladyofthelog pls drop anything you think should be part of this ticket here

**Comment by Candleja** [comment]
merely doing a GET request to the /works/new/ endpoint shouldn't create a new (empty) work, imo, because that means if you refresh the page or someone just links you to it, you'll get littered with drafts

oh haha, i just realized this violates idempotence, you really do need to change it

**Comment by Candleja** [comment]
GET requests to the /works/:id/chapters/new endpoint should also not create a new chapter, for the same reason

**Comment by Candleja** [comment]
"bulk publish" support for chapters when publishing a work could be a worthwhile consideration (unclear if worth doing as part of MVP).

use case:
if i upload multiple chapters of my fic before publishing any of them, then i do not want to have to click back and forth from the work to each individual chapter to manually publish them one at a time

it could be potentially addressed in the UI with either a checkbox situation on the /works/:id/edit/ page in the "edit chapters" view, or as a "publish all unpublished chapters" button on the "edit work" view



EDIT: WAIT NEVERMIND i found the publish button it wasn't where i was expecting it, but "click thru to each chapter and click publish from that view" works just fine for me actually and would be fine

**Comment by Candleja** [comment]
publishing a chapter sends you to back to chapter 1, but it'd be nicer if it sent you to the chapter you just published instead

**Comment by c-e-p** [comment]
@Candleja yeah this (https://github.com/c-e-p/ourchive/issues/48#issuecomment-1574572602) is a common workflow in posting is what i found when researching, and my thought was that it might make sense to keep the workflow, which many users love for some fucking reason, but put drafts in a delete queue if they're untouched BUT that might be complicating it a bit. i'll noodle with it a bit more

**Comment by c-e-p** [comment]
@Candleja what do we think about a big ole 'publish all' button on the work edit view? this was my plan basically in addition to the non-form-view controls

**Comment by Candleja** [comment]
@c-e-p 

imo if you really wanna keep the workflow of "if you click the 'new work' menu option you get a free draft created" you should make the url in the menu bar trigger a POST request to the endpoint instead of a GET, and then have the response be a redirect to GET /works/:id instead of /works/new

i have no objections to the workflow conceptually, im just clutching my pearls over a GET request being unsafe/not read-only

I think a "publish all" button would be perfect

**Comment by c-e-p** [comment]
@Candleja well i think the headless architecture is obscuring what's going on a little - you make the GET to the frontend URL, the view then calls the API, which POSTs to create a new work. but obvi creating a bunch of drafts isn't ideal. i'm going to play around with a "save this work?" on nav away option or just create the work upon navigating away within the "edit view" (e.g. save when you nav to chapters -- which is an existing issue anyway -- but not when you load the page) or prompt the user to save/discard a draft

**Comment by Candleja** [comment]
ooooooh ok that's fine then yeah, chrome's network monitor wasn't catching that fast enough so i got confused about what was doing what, sorry haha

what do you think about (and i don't know about this, it sounds weird):

if you have one empty draft, it doesn't create a new empty draft, but instead pulls up the existing empty for edits? i can't see any situations where someone would want multiple empty drafts, and that would help with the "lol i went to my works page and now i have 10 blank drafts oops"

**Comment by c-e-p** [comment]
@Candleja oh yeah that's a really good flow and easy enough to implement. that's what we'll go with

**Comment by ladyofthelog** [comment]
Linking to my UI proposal doc here as well: https://docs.google.com/document/d/1zN28nOTC6KONu7MDTAoLCx0sbrvPYhLx6sRGMCI9WRU/edit

**Comment by c-e-p** [comment]
Instead of pagination, added a non-paginated view to fetch chapter data. This will obviously slow down chapters past 20 or so, which I think is fine. If we see issues filed we can always add pagination, but it's medium complexity given the complexity of the edit form, and frankly I am in favor of the design discouraging massive 50+-chapter works.

**Comment by c-e-p** [comment]
This is wrapped up in dev, @ladyofthelog moving to test for you to review if you want
