### ISSUE TITLE
Enhanced Tagging

### ISSUE THREAD

**Issue by c-e-p** [c-e-p/ourchive#50]
Currently, tagging only applies to works & bookmarks. 

Should we add tagging to chapters? What about users?

**Comment by c-e-p** [comment]
- Add a 'user tag?' option to tag types, if set to true then that tag type is available for users to add tags to when editing profiles; add 'limit to users?' option which specifies the tag type is *only* for user profiles
- All tag types are system administered so if a need arises to limit what tags a user can add to themselves, you can set it to system administered
- Example user tag use cases: some archives might make fandom & pairing tag types apply to users (in addition to works/bk.etc). Alternatively, you could create an 'interest' tag type limited to user profiles which allows users to tag themselves by general interest(s).

**Comment by Candleja** [comment]
I think allowing tagging to chapters would encourage more of the "make an anthology fic that has a separate minific as each chapter" behavior that sometimes happens on AO3 -- but at the same time, allowing people to see/search tags _by_ chapter could make "seeing someone's anthology fic when browsing/search" less annoying to read.

Would that be desirable or would that be annoying?

**Comment by c-e-p** [comment]
@Candleja i think maybe both but series/work collections should also be on this roadmap which might help alleviate that if they were a first class feature instead of a "dumb" container -- will add to this roadmap
