### ISSUE TITLE
Chapter Tag Support

### ISSUE THREAD

**Issue by c-e-p** [c-e-p/ourchive#53]

**Comment by Candleja** [comment]
As a reader:

If someone posts a 30-chapter work titled "Kinktober", comprised of 15 different pairings and 45 different kinks, where each chapter is independent of the others, I just want some way to find out "Does Pairing A do kink Y, and if so, in which fucking chapter?"

When I am reading a work, if an author puts new ("not attached to the work as a whole") tags on a chapter, I want to be able to view those tags before proceeding to the next chapter.

**Comment by Candleja** [comment]
As an author:

I would want to be able to apply some tags to my entire work ("Pairing A, trope B, event C"), while also applying certain tags to only a specific chapter ("graphic violence", "explicit smut", "weird kink", "Pairing B"), to let my readers have a better understanding of what's in my work and where to skip to if they want to find/avoid something.
