### ISSUE TITLE
Unsuccessful Login Message is hard to find in UI TESTS

### ISSUE THREAD

**Issue by klreeher** [c-e-p/ourchive#65]
On the ourchive login page, when you have an unsuccessful login, currently a little ui notification pops up with a message, and disappears after a few seconds. 

![ui notification script in the page source](https://github.com/c-e-p/ourchive/assets/1613107/f66cd415-ebd8-46c3-9ac2-05d6690c728d)

In the UI Tests, when I'm looking for this pop up, it's a little tricky as the div created doesn't have an id. While I can find the element by xpath (relative location of div + text in message) this can occasionally run into race conditions where the search time is longer than the timeout on the pop up div.

![pop up dive shown in the page source](https://github.com/c-e-p/ourchive/assets/1613107/49baa401-3644-4742-a4ae-634080291513)

two solutions spring to mind:
1. add an id to the div or something so i can find it faster
2. close the div on a different trigger -- either focus click away or a boring close button.

**Comment by c-e-p** [comment]
i fixed it i think @klreeher
